const { authenticator } = require("otplib");

const secret = "2FA key goes here"; // 2FA key - can be retrieved by resetting your current 2FA and copying the key generated by loop

async function login(page) {

  await page.goto("https://autoloop.us/DMS/App/Notifications");


  await page.type("#Username", "rkomprath@autoloop.com");
  await page.click("#action_next-step");


  await page.waitForSelector("#Password");


  await page.type("#Password", "******"); // password goes where the *'s are
  await page.click("#action_sign-in");

  await page.waitForSelector("#totpCode");
  const token = authenticator.generate(secret);
  await page.type("#totpCode", token);
  await Promise.all([
    page.waitForNavigation(),
    page.click(
      "#login-form > div.row.justify-content-between > div.col-md-6.text-right > button"
    ),
  ]);
}

module.exports = login;
